# -*- coding: utf-8 -*-
"""DESAFIO1-SEL-CONSTRUCCION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gOaTa_J6CIxDtdV610A992tMn8jBa_px
"""

import numpy as np

# Definir la matriz A
A = np.array([[52, 20, 25],
              [30, 50, 20],
              [18, 30, 55]])

# Definir el vector b
b = np.array([4800, 5810, 5660])

# Calcular la inversa de A
A_inv = np.linalg.inv(A)

# Calcular el vector x
x = np.dot(A_inv, b)

# Imprimir los resultados
print("Matriz A:")
print(A)
print("\nVector b:")
print(b)
print("\nInversa de A:")
print(A_inv)
print("\nSolución del sistema (x):")
print(x)